### PR TITLE
SA-1 Hostel Management

### PR DESCRIPTION
**Pull request by anujpatel03**
## Issue that this pull request solves
PR #1422 
Closes: # (issue number)

### Brief description of what is fixed or changed

Added migrations files in all the modules.

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

@ChaudharyRaman  Added migrations files in all the modules.

### CODE REVIEW

**Comment by Priyansh61** [comment]
@anujpatel03 Kindly fill the PR description completely, it is difficult for us to merge PR without that.. And add a demo video of working module for review reference.

**Comment by anujpatel03** [comment]
> @anujpatel03 Kindly fill the PR description completely, it is difficult for us to merge PR without that.. And add a demo video of working module for review reference.


Final [Video Link](https://drive.google.com/file/d/1sNdo_v3CW9nG61LLYlEyMb8osCdklLaW/view?usp=drive_link) which was of PR #1422

In this PR I have only added migrations files in all the modules.

**Comment by Aragorn-64** [comment]
@Priyansh61 looks good to me
Only migrations have been added and one SA-1 view file changed.
Video demonstration was brief but seems to be working

**Comment by Priyansh61** [comment]
@Aragorn-64 Can you and @anujpatel03 once get in a meet and see if everything works fine and we can push the module to staging then?

**Comment by Aragorn-64** [comment]
@Priyansh61 This and PR[#1422](https://github.com/FusionIIIT/Fusion/pull/1422) combined look fine. Can merge to staging for evaluation

**Pull request merged**
