### PR TITLE
SA-1 : Hostel Management (Fixed Bugs)

### PR DESCRIPTION
**Pull request by anujpatel03**
## Issue that this pull request solves

Closes: # (issue number)

### Brief description of what is fixed or changed

In all the forms phone number checks were having issue of length and type , now it has been resolved.
Added room type in guest room booking ,added edit fine , added edit and remove student information.

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

@varun7singh @ChaudharyRaman @prajjwalkapoor Kindly Merge this PR , This is updated one.
If there is any conflict then let me know.

### CODE REVIEW

**Comment by anujpatel03** [comment]
[Video Link](https://drive.google.com/file/d/1sNdo_v3CW9nG61LLYlEyMb8osCdklLaW/view?usp=sharing) (Open with college id only)

**Comment by theoden42** [comment]
> [Video Link](https://drive.google.com/file/d/147UhEZOOXc2MLlUeC9-NlpWJSOrWGtfi/view?usp=sharing) (Open with college id only)

@anujpatel03 can you provide a brief description of what were the issues and what are the fixes implemented? Thanks.

**Comment by anujpatel03** [comment]
> > [Video Link](https://drive.google.com/file/d/147UhEZOOXc2MLlUeC9-NlpWJSOrWGtfi/view?usp=sharing) (Open with college id only)
> 
> @anujpatel03 can you provide a brief description of what were the issues and what are the fixes implemented? Thanks.

In all the forms phone number checks were having issue of length and type , now it has been resolved.
Added room type in guest room booking ,added edit fine , added edit and remove student information.

**Comment by prajjwalkapoor** [comment]
LGTM.

**Pull request merged**
