### PR TITLE
Fixing issue #939 (Feedback button does not highlight on hover)

### LINKED ISSUE #939: Feedback button not highlighting on hover.
**Describe the bug**
In the dashboard navbar, the "Feedback" button is not highlighting on hover.

**To Reproduce**

1. Log in to your account
2. On the dashboard, hover on the "Feedback" button in the navbar.
3. As it can be clearly seen, all other navbar buttons highlight on hover, Feedback button doesn't.

**Expected behavior**
Feedback button should also highlight on hover.
Screenshot (2222)
Screenshot (2223)

**Screenshots**
Attached.

This can be easily fixed by moving the 'div' tag inside the 'a' tag and adding appropriate classes.

### PR DESCRIPTION
**Pull request by AryanWadkar**
## Issue that this pull request solves

Closes: #939

## Proposed changes

div and anchor tag have been swapped and appropriate classes have been applied.

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by garvitgupta13** [comment]
@AryanWadkar attach a screenshot after your changes

**Comment by garvitgupta13** [comment]
@AryanWadkar attach a screenshot after your changes

**Comment by AryanWadkar** [comment]
Here is the screenshot after my changes.
image

**Review by garvitgupta13 — APPROVED** [review]
@akanimesh please merge it

**Pull request closed without merging**
