### PR TITLE
Ps1 : Week 7 : Dev -> endpoint created for filing indent with multiple items

### PR DESCRIPTION
**Pull request by kanha638**
## Proposed changes
Created endpoint as well as new form for creating/filling indent with multiple items.

### Brief description of what is fixed or changed
`/purchase-and-store/create_indent_multiple` endpoint has been added which will be taking care of the Indent with multiple items form.

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Screenshot 2023-03-12 at 7 09 57 PM

Screenshot 2023-03-12 at 7 10 15 PM

### CODE REVIEW

**Comment by kanha638** [comment]
@harshp0702 please review and approve the PR.

**Review by harshp0702 — COMMENTED** [review]
Approved. @akshatnema

**Comment by kanha638** [comment]
@akshatnema before merge this pr #1142 should be approved and merged by the DB head as it contains Database related changes.

**Comment by akshatnema** [comment]
Ok, so this PR should be merged after #1142 is approved and merged :+1:

**Comment by akshatnema** [comment]
Waiting for the review from @PranshuNayak and @samay-rgb

**Review by samay-rgb — APPROVED** [review]

**Review by PranshuNayak — APPROVED** [review]

**Pull request merged**
