### PR TITLE
ps-2: week 12: Report generation functionality added

### PR DESCRIPTION
**Pull request by gaganmeena05**

### CODE REVIEW

**Comment by rakshit512002** [comment]
LGTM @akshatnema

**Review by PranshuNayak — COMMENTED** [review]
changes in models.py are not needed. The table is already migrated to the database with the same fields.

**Comment by akshatnema** [comment]
Review required from @PranshuNayak

**Comment by akshatnema** [comment]
@gaganmeena05 Pranshu asked you to undo the changes on the file, not to delete it.

**Review by PranshuNayak — COMMENTED** [review]
Could you remove migrations and models.py from this PR, you have deleted and pushed them.

**Pull request merged**
