### PR TITLE
Gad1 : Week4 :  Added design departments tab and some new subtabs for all departments

### PR DESCRIPTION
**Pull request by CHOUHAN-MOHIT**
## List of changes
-  [x] Added  design department tab on the departments homepage
-  [x]  Added alumni and track record subtabs for all departments
-  [x] Restored user profile card on department page.

## Screenshots

image

### CODE REVIEW

**Review by Sha2nkGitHub — COMMENTED** [review]
Approved. Ping @akshatnema 
Ping @manavdesai27

**Review by Sha2nkGitHub — COMMENTED** [review]
Approved.
Ping @akshatnema 
Ping @manavdesai27

**Comment by manavdesai27** [comment]
@CHOUHAN-MOHIT Kindly resolve the merge conflicts, only after that we can merge.

**Review by Sha2nkGitHub — COMMENTED** [review]
Approved
Ping @akshatnema @manavdesai27

**Review by Sha2nkGitHub — COMMENTED** [review]
Approved.
Ping @akshatnema
Ping @manavdesai27

**Comment by CHOUHAN-MOHIT** [comment]
resolved conflicts

**Pull request merged**
