### PR TITLE
OS-2 : Week 2 : Time Validation while booking doctor's appointment

### LINKED ISSUE #1020: Web Group OS-2 - Time Validation for booking a doctor's appointment
**Describe the bug**
There isno validation for time while booking doctor's appointment.

**To Reproduce**

1. Go to 'http://localhost:8000/healthcenter/student/'
2. Click on 'Appointments/Requests'
3. Fill the form.

**Expected behavior**
An alert message should be shown notifying the user about the error.

### PR DESCRIPTION
**Pull request by divyanshkhetan**
## Issue that this pull request solves

Closes: #1020 

## Proposed changes
- Add a validation on clicking the submit button.

### Brief description of what is fixed or changed
- A validation is added for the time while booking the appointment.

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image

### CODE REVIEW

**Review by NuthanReddy646 — COMMENTED** [review]
Approve @akshatnema

**Comment by akshatnema** [comment]
@divyanshkhetan correct your PR title

**Comment by divyanshkhetan** [comment]
@akshatnema Done.

**Comment by akshatnema** [comment]
@divyanshkhetan Kindly resolve the merge conflicts as all the PRs will be merged to test branch and also merge the latest changes of the test branch.

**Pull request closed without merging**
