### PR TITLE
Updated Ac2 merged with staging

### PR DESCRIPTION
**Pull request by Divyanshusir**
## Solving the issues in gitignores , migrations
#merged with latest staging

### CODE REVIEW

**Comment by Divyanshusir** [comment]
@ChaudharyRaman  @prajjwalkapoor Please merge this pr.

**Comment by theoden42** [comment]
@Divyanshusir  Have you rebased/merged this PR with the latest_staging branch on your local?

**Comment by theoden42** [comment]
Also please include what changes have been made in this PR providing the description about which module have been effected, so it is easy to review. Thanks!

**Comment by Divyanshusir** [comment]
@theoden42  I have specifically done changes in ac-2 (academic-procedures) folder and corrected gitignore file , then i fetched latest_staging and merged it, so any changes done in latest_staging are also present.
I haven't made any changes in other modules code by myself.

**Comment by theoden42** [comment]
In that case, LGTM

**Review by theoden42 — APPROVED** [review]
Only changes specific to this module are in .gitignore which is checked. All other module changes have been picked from latest_staging branch.

**Comment by abhi87374** [comment]
@ChaudharyRaman @prajjwalkapoor  LGTM , you can proceed

**Comment by ChaudharyRaman** [comment]
okay LGTM, Merging.

**Pull request merged**
