### PR TITLE
Group #15 : Code Refactoring

### PR DESCRIPTION
**Pull request by supr158**
- Added docstrings for functions and model classes.
- Renamed variables according to instructions given.
- Added utils.py file.

### CODE REVIEW

**Comment by supr158** [comment]
@anurag0singh please review this PR.

**Review by anurag0singh — APPROVED** [review]
@MananJethwani please merge this PR.

**Review by anurag0singh — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts @supr158

**Comment by supr158** [comment]
Resolved merge conflict.You can check @anurag0singh

**Pull request merged**
