### PR TITLE
ac-3 : week-5 : Fixed Assignment and slide upload and download by Instructor

### PR DESCRIPTION
**Pull request by tech-akash**
## Issue that this pull request solves

Closes: #1061 

### Brief description of what is fixed or changed
Now Instructor can upload ,view and download Assignment and slide provided by him.
## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by PranshuNayak — COMMENTED** [review]
LGTM!

**Review by samay-rgb — COMMENTED** [review]
LGTM

**Comment by abhishekkumar5606** [comment]
LGTM

**Comment by PranshuNayak** [comment]
@tech-akash please push the migration for db changes.

**Pull request merged**
