### PR TITLE
Central Mess Module: Fix to module not opening issue

### PR DESCRIPTION
**Pull request by abhishek-geek**
Linked Issue: #489

### CODE REVIEW

**Comment by abhishek-geek** [comment]
@akanimesh At this point, we have a temporary solution for issue #489 (Task 1). The complete solution can be made by redirecting the user to a form page if the user is not registered yet in the mess_info database. I am working on the same.

**Comment by MananJethwani** [comment]
@akanimesh kindly review this PR asap so it can be merged.

**Comment by akanimesh** [comment]
> @akanimesh kindly review this PR asap so it can be merged.

It's just a temporary fix. @abhishek-geek  redirect the user to a Form and use that data to create a db instance for mess_info.

**Comment by abhishek-geek** [comment]
> > @akanimesh kindly review this PR asap so it can be merged.
> 
> It's just a temporary fix. @abhishek-geek redirect the user to a Form and use that data to create a db instance for mess_info.

me and @abhi178134 are working on the same.

**Pull request merged**
