### PR TITLE
SA-3 : Resolved merge conflicts and tested execution

### PR DESCRIPTION
**Pull request by Anurag607**
- Implemented the use cases for each actor as per the use case diagram created and approved by faculty mentor (attached below) [in the /FusionIIIT/applications/gymkhana directory]
- Implemented the APIs to be used in the android application [in the /FusionIIIT/applications/gymkhana/api directory]
- Added migrations [in the /FusionIIIT/applications/gymkhana/migrations directory]

### Use Case Diagram: 
UCD_SA3

### Video:
https://drive.google.com/file/d/1a53lZGFBzO5cGyBHCWJFtqisF1DKVDMJ/view?usp=sharing

### CODE REVIEW

**Comment by Anurag607** [comment]
@ChaudharyRaman @varun7singh ptal

**Comment by Anurag607** [comment]
There are a issues to be resolved concerning the database please hold while the issues get resolved.

**Comment by Priyansh61** [comment]
@Anurag607 What's the current status ? Can you please update us ?

Also kindly update the PR template with all the details...

**Comment by Anurag607** [comment]
> @Anurag607 What's the current status ? Can you please update us ?
> 
> Also kindly update the PR template with all the details...

There are few use cases which are causing conflicts upon execution, my team is working on resolving them. Once the issues get resolved I will be notifying you of the changes.

**Comment by Anurag607** [comment]
@Priyansh61 PTAL

**Comment by Anurag607** [comment]
@Priyansh61 @ChaudharyRaman @varun7singh @Shivkant-Chauhan any updates regarding the review?

**Comment by ChaudharyRaman** [comment]
@prabhatsuman @anudeeps0306 Please take a look !! LGTM, Please check once for any changes...

**Comment by anudeeps0306** [comment]
@Anurag607 you need to change 0001_inital.py in all modules , use the old file present in main branch.

**Comment by anudeeps0306** [comment]
@ChaudharyRaman Everything looks good now.

**Pull request merged**
