### PR TITLE
Group7-IWDModule-UI and Database Schema

### PR DESCRIPTION
**Pull request by sansax27**
Please read the description of every commit and in case of doubt, contact us. Also, database schema is given through models.py file and not diagramatically(As it has been already submitted to PSG Group), but if demanded it can be easily provided.

### CODE REVIEW

**Comment by garg3133** [comment]
@sansax27 Can you remove the UI part from this PR and create a new issue with title `<Your module name> UI Design` and add the screenshots there in the description?

**Comment by sansax27** [comment]
> 
> 
> @sansax27 Can you remove the UI part from this PR and create a new issue with title `<Your module name> UI Design` and add the screenshots there in the description?

Sure

**Comment by sansax27** [comment]
Done and review it.

**Comment by sansax27** [comment]
Wrong schema image was uploaded. Please review new one.

**Pull request closed without merging**
