### PR TITLE
corrected ac-4 module

### PR DESCRIPTION
**Pull request by xenouno**
## Issue that this pull request solves

Closes: # (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by xenouno** [comment]
@prabhatsuman verify it

**Comment by prabhatsuman** [comment]
LGTM

**Comment by Kaushals112** [comment]
[https://drive.google.com/file/d/1SdOOAijuSLoagEaxu5xVBR1lIr_bMUZb/view?usp=sharing](url) the final functional video link

**Comment by Kaushals112** [comment]
https://drive.google.com/file/d/1SdOOAijuSLoagEaxu5xVBR1lIr_bMUZb/view?usp=sharing

**Comment by Kaushals112** [comment]
https://drive.google.com/file/d/1SdOOAijuSLoagEaxu5xVBR1lIr_bMUZb/view?usp=sharing

**Comment by Kaushals112** [comment]
> [https://drive.google.com/file/d/1SdOOAijuSLoagEaxu5xVBR1lIr_bMUZb/view?usp=sharing](url)

**Pull request merged**
