### PR TITLE
Ps-1 Changes

### PR DESCRIPTION
**Pull request by ThisisMS11**
## Features implemented
1.  Implemented file tracking SDK in inbox, file forwarding, file creation and in various places.
2.  Added Outbox API's and It is implemented using file tracking SDK.
3.  Added global transfer execution and dept transfer execution functionality.
4.  Corrected the existing code for various API's. 
5.  Fetched the new Dashboard changes. 
6.  Implemented Stock Transfer between departments by dept_admin and ps_admin
7.  Added Apis for obtaining individual stock Item information like current_department,physical location .
8.  Implement filter based lookup for stocks belong to different departments.

## Types of changes

Put an x in the boxes that apply

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

Put an x in the boxes that apply

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

Video Explaination for changes : https://drive.google.com/file/d/1gZTVEtmbG3Nn0B47LqcmYRcy0Bt94AQp/view?usp=sharing

### CODE REVIEW

**Comment by ThisisMS11** [comment]
@varun7singh please review the PR .

**Comment by VarunGitGood** [comment]
@ThisisMS11 keep the migrations according to the latest rules discussed

**Comment by ThisisMS11** [comment]
So do I need to keep the migrations as they were in local system during development? 
Please share the new rules.

**Comment by ThisisMS11** [comment]
here is the PR with migrations https://github.com/FusionIIIT/Fusion/pull/1430 .

**Pull request closed without merging**
