### PR TITLE
Gad 2 New Commits

### PR DESCRIPTION
**Pull request by Srivatsa19**
## Issue that this pull request solves
Added functionality where only logged in users can access the module. The module has been implemented according to the use case diagram
Closes: # (issue number)

## Proposed changes
1. Error Handling where users were able to access the module without logging in.
2. Fixed the drop down with the correct designations on line 818 in the views.py file.
## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
https://drive.google.com/drive/folders/1iQBxUOuhojei7qLjph9K1bhximrseokW?usp=sharing
Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

The designations used in the module are :-
designations_list = ["Junior Engineer", "Executive Engineer (Civil)", "Electrical_AE", "Electrical_JE", "EE", "Civil_AE", "Civil_JE", "Dean (P&D)", "Director", "Accounts Admin", "Admin IWD", "Auditor"]

ajay --> Junior Engineer
dvijay --> Executive Engineer (Civil)
de --> Dean (P&D)
dir --> Director
richard --> Accounts Admin
iwdAdmin --> Admin IWD
kunal --> Auditor

@varun7singh
@ChaudharyRaman
@prajjwalkapoor

### CODE REVIEW

**Comment by Aragorn-64** [comment]
@Srivatsa19 please fill the format of the PR, add relevant information and add screenshots + usage video

**Comment by Aragorn-64** [comment]
Filetracking part seems to work properly, and PR format is followed. Looks good

**Comment by Aragorn-64** [comment]
I think its ready to merge @prajjwalkapoor

**Comment by prajjwalkapoor** [comment]
LGTM, merging.

**Comment by anudeeps0306** [comment]
FusionIIIT/applications/globals/api/views.py, I talked with the dashboard team, and this change is not supposed to be here.
0001_initial.py has been changed, which will cause an error during migrations. Hence you need to remove these lines.

**Pull request merged**
