### PR TITLE
SA-3 : Implemented Use Cases for Each Actor as per UCD

### PR DESCRIPTION
**Pull request by Anurag607**
- Implemented the use cases for each actor as per the use case diagram created and approved by faculty mentor (attached below) [in the /FusionIIIT/applications/gymkhana directory]
- Implemented the APIs to be used in the androind application [in the /FusionIIIT/applications/gymkhana/api directory]
- Added migrations [in the /FusionIIIT/applications/gymkhana/migrations directory]

### Use Case Diagram: 
UCD_SA3

### Video:
https://drive.google.com/file/d/1WGUPHmgKnbs7yCFFfcyGfkP__qQsYIga/view?usp=sharing

### CODE REVIEW

**Comment by varun7singh** [comment]
Hey @Anurag607 please add a demo video and code explanation
Thanks!

**Comment by varun7singh** [comment]
And all the migrations files

**Review by VarunGitGood — CHANGES_REQUESTED** [review]
Hey @Anurag607 please add a demo video and code explanation
And all the migrations files
Thanks!

**Comment by Anurag607** [comment]
@varun7singh I have updated the PR description with a demo video. PTAL

**Review by VarunGitGood — CHANGES_REQUESTED** [review]
Please remove the migrations files

**Comment by Anurag607** [comment]
@varun7singh the migrations file has been removed

**Comment by VarunGitGood** [comment]
There are still some migration files left also please merge into SA3 not main

**Comment by VarunGitGood** [comment]
@Anurag607 we have some merge conflicts too please resolve them and remove the migrations files use 
```
**/migrations/*
```
in gitignore that should do it

**Comment by Anurag607** [comment]
@varun7singh I have updated the base branch and removed all the migrations, PTAL.

**Comment by VarunGitGood** [comment]
@Anurag607 there are multiple conflicts please resolve them

**Pull request closed without merging**
