### PR TITLE
Gad 2 2025 latest

### PR DESCRIPTION
**Pull request by Srivatsa19**
## Issue that this pull request solves
Merge conflicts resolved.
Closes: # (issue number)

## Proposed changes
There were merge conflicts and this is the resolved PR
## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
https://drive.google.com/drive/folders/1iQBxUOuhojei7qLjph9K1bhximrseokW?usp=sharing
Please attach the screenshots of the changes made in case of change in user interface

## Other information
@varun7singh
@Priyansh61
@prajjwalkapoor
@ChaudharyRaman
Any other information that is important to this pull request

### CODE REVIEW

**Comment by abhi87374** [comment]
@ChaudharyRaman any specific reason for not adding .idea file to gitignore ?,
I got to know from RSPC module team too , that you suggested them to do so.

**Comment by ChaudharyRaman** [comment]
@Srivatsa19 Can you please pull from the `latest_staging`.

**Comment by Srivatsa19** [comment]
> @Srivatsa19 Can you please pull from the `latest_staging`.

I pulled from the latest_staging and resolved the merge conflicts and this is the PR after resolving the conflicts.

**Comment by Srivatsa19** [comment]
> @Srivatsa19 Can you please pull from the `latest_staging`.

Pulled from latest_staging.

**Review by Priyansh61 — APPROVED** [review]

**Pull request merged**
