### PR TITLE
gad-3 : week-8 : db migrations after adding Section Incharge

### PR DESCRIPTION
**Pull request by ujjawallele13**
### Brief description of what is fixed or changed

1. made null=True in secincharge_id in workers in models.
2. changed name of some AREA in models.
3. created a new class SectionIncharge.
4. changed the field caretaker_id to secincharge_id in workers in models.

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Comment by ujjawallele13** [comment]
please review it @PranshuNayak @Arnav511.

**Review by PranshuNayak — APPROVED** [review]
@samay-rgb

**Review by samay-rgb — APPROVED** [review]

**Comment by ujjawallele13** [comment]
Link of previous PR related to this PR
https://github.com/FusionIIIT/Fusion/pull/1132

**Comment by ujjawallele13** [comment]
Please deploy it @akshatnema @Aksh-Bansal-dev @yatharthagoenka .

**Pull request merged**
