### PR TITLE
Purchase and Store Pull Request 

### PR DESCRIPTION
**Pull request by ThisisMS11**
## Features implemented
1.  Added generate global report and generate dept report functionality.
2.  Implemented file tracking SDK in inbox, file forwarding, file creation and in various places.
3.  Added Outbox API's and It is implemented using file tracking SDK.
4.  Added global transfer execution and dept transfer execution functionality.
5. Corrected the existing code for various API's. 6.  Fetched the new Dashboard changes. 

## Types of changes

Put an x in the boxes that apply

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

Put an x in the boxes that apply

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

Link to Video Explanation : https://drive.google.com/file/d/1UoS6oRsB8OB9jUFHe4GVqRX9eZc2q80q/view?usp=sharing

### CODE REVIEW

**Comment by VarunGitGood** [comment]
Please resolve merge conflicts and remove migrations

**Comment by ThisisMS11** [comment]
If we don't want migrations to be a part of our codebase , why no one has ever put /migrations  in the gitignore file ?

**Comment by VarunGitGood** [comment]
Well please be the first I've asked most of them to add them seperately in gitignore

**Comment by ThisisMS11** [comment]
We have not removed some migrations files as when we tried to regain the migrations after deleting the migrations mentioned in files changes section the  following error was there : 

raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration academic_information.0001_initial dependencies reference nonexistent parent node ('programme_curriculum', '0001_initial')

so for now we have kept some migrations file , in later pushes we may remove these also .

**Pull request closed without merging**
