### PR TITLE
Bonafide, Dues, Attendance and check CPI - Academic Module

### PR DESCRIPTION
**Pull request by get-thepacket**
- Bonafide can be downloaded by providing purpose.
- Dues can be checked
- Attendance can be checked
- CPI can be checked.

### CODE REVIEW

**Review by ajwad-shaikh — COMMENTED** [review]
Looks good. Awaits testing. Requesting testing review from @salarx or @manavgoyal53

**Review by salarx — APPROVED** [review]
Looks good. Shouldn't break anything.

**Review by manavgoyal53 — CHANGES_REQUESTED** [review]
Testing Remaining.

**Review by manavgoyal53 — APPROVED** [review]

**Comment by salarx** [comment]
Merging now.

**Pull request merged**
