### PR TITLE
GAD -5 Dashboard Changes

### PR DESCRIPTION
**Pull request by BlackHAWK2001**
## Issue that this pull request solves

Closes: # (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by BlackHAWK2001** [comment]
@varun7singh

**Review by VarunGitGood — CHANGES_REQUESTED** [review]
Add demo video and explain the code changes

**Comment by BlackHAWK2001** [comment]
## Added Functionality: Selecting Multiple Designations and Accessing Current Designation

### Changes Made
- Implemented the ability to select multiple designations from the dropdown menu in the global navbar.
- Added a signal triggered on user login to set the designated role for the user.
- Introduced a global variable named `global_var` to store the current selected designation for accessibility across modules.
- Set the default designation to be either staff, student, or faculty based on user role.

### Usage
- Users can now choose multiple designations from the dropdown.
- The signal on user login ensures that the user's designation is set accordingly.
- The global variable `global_var` holds the current selected designation for easy access across modules.


Video drive link : https://drive.google.com/file/d/1I31UDgeHior_RrpOa8Y-SI7H94Ud0fRf/view?usp=drive_link

**Comment by BlackHAWK2001** [comment]
@varun7singh

**Comment by VarunGitGood** [comment]
LGTM

**Pull request merged**
