### PR TITLE
GAD - 4 : Create File Tracking SDK and make the Web Application completely functional

### PR DESCRIPTION
**Pull request by theoden42**
## Issue that this pull request solves
 1. Web Views for inbox, outbox, archiving, drafts, forwarding, and history of the file were not working properly
 2. Templates were incorrect and did not show data in correct order
 3. View file template and view were not present
 4. File and Tracking Model lacked field for generalisation (API for other modules) 
 5. Seriallizers were not present for the data

Closes: # (issue number)

## Proposed changes
1. Updated the models for generalisation 
2. Create Comprehensive filetracking SDK 
3. Use Filetracking SDK methods to implement required views and fix incorrect ones
4. Update Templates for inbox, outbox, drafts, archive and others
5. Add templates which are missing eg: view_file, finish_file

### Brief description of what is fixed or changed
The filetracking sdk now includes methods for implementation of workflow in other modules. The filetracking web view is now functional for employees and they can view, send, track, forward, archive, draft the files with attachments. 

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by theoden42** [comment]
@prajjwalkapoor please review

**Comment by prajjwalkapoor** [comment]
@theoden42 LGTM. 
Just make a small walkthrough video.

**Comment by theoden42** [comment]
Sure. Here is the walkthrough of the web interface @prajjwalkapoor. 
[video](https://drive.google.com/file/d/13sBSrZoGz1fASgkCziM4x6wq5n_CwCLo/view?usp=drive_link)

**Comment by prajjwalkapoor** [comment]
@Kushagra-Yadav 
@abhi87374⁰
@Kunal-2417

Do check if we can integrate this with the main.

**Pull request merged**
