### PR TITLE
ac-3 : resolve error, add api

### PR DESCRIPTION
**Pull request by Daksh119**
## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes
1. Added a new API related UI and Schema for instructors
2. Course management now has Acad admin as a user
3. 2 APIs and related UI added for the Acad admin

### Brief description of what is fixed or changed
1. UI bug fixes and improvements for Student and Instructor
2. Urls the fetch media from the database changed
3. Resolved errors in previouly implemented APIs

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Review by VarunGitGood — CHANGES_REQUESTED** [review]
Please add a demo video and remove the migrations files 
Thanks!

**Comment by Shivkant-Chauhan** [comment]
> Please add a demo video and remove the migrations files Thanks!

dont ask folks to remove migration artifacts

**Comment by Daksh119** [comment]
demo video : 
[https://drive.google.com/file/d/1SYhN6p-sR6xAOc-NU7a4Ofas1Rjyz63y/view?usp=drive_link](url)

**Comment by Daksh119** [comment]
Demo video: https://drive.google.com/file/d/1SYhN6p-sR6xAOc-NU7a4Ofas1Rjyz63y/view?usp=drive_link

**Comment by Daksh119** [comment]
@ChaudharyRaman

**Pull request merged**
