### PR TITLE
OS-2 : Week 5 : Fixed Doctor's Model and removed some hard-coded values

### PR DESCRIPTION
**Pull request by divyanshkhetan**
## Issue that this pull request solves
- Doctor's Model has some fields of wrong data type.
- Doctor's name is hard-coded at all places.

## Proposed changes
- Fix doctor's model and implement the fixed model at all places.

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image
image
image

### CODE REVIEW

**Review by NuthanReddy646 — COMMENTED** [review]
Approve @akshatnema

**Comment by akshatnema** [comment]
Review required from @PranshuNayak and @samay-rgb

**Review by PranshuNayak — COMMENTED** [review]
Push the migrations that were generated due to changes in Doctors model , they must be present inside the migration folder of health center.

**Review by samay-rgb — APPROVED** [review]

**Comment by divyanshkhetan** [comment]
@PranshuNayak @akshatnema @samay-rgb please merge this PR asap

**Comment by manavdesai27** [comment]
@PranshuNayak Please approve this PR.

**Review by PranshuNayak — APPROVED** [review]

**Pull request merged**
