### PR TITLE
Issue FusionIIIT#570 resolved

### PR DESCRIPTION
**Pull request by supr158**
Issue resolved

- Adding 'required' tag in input field for room.no resolved the exception at edit_student/.
-  Now,confirmation is asked before deletion

Screenshot from 2022-02-03 15-41-42

### CODE REVIEW

**Comment by supr158** [comment]
@anurag0singh please review this PR.

**Review by anurag0singh — COMMENTED** [review]
Please add some kind of warning when no pdf is uploaded. For example:
image

**Comment by supr158** [comment]
@anurag0singh I have added warning.You can check it to verify.

**Review by anurag0singh — APPROVED** [review]
Approved. @MananJethwani please merge this PR.

**Pull request merged**
