### PR TITLE
Updated PR AC2-Course registration after the changes and integration with new Dashboard

### PR DESCRIPTION
**Pull request by Divyanshusir**
## Changes made as suggested:
In sync with new dashboard
In sync with new programme_curriculum_course table with new version column.
New Pre registration logic without priority system.
New Replace course feature for optional elective courses.
New Swayam replace option for replacing optional courses with swayam courses.

Bugs and issues Fixed:
student courses and drop option from acad admin side of it was fixed, 
roll number input (type = number) field issue fixed

Video : 

https://github.com/FusionIIIT/Fusion/assets/114430068/ba07781d-ab56-4795-be83-ed0f691f6a35

Please merge this PR and if any issues please let me know:
@ChaudharyRaman
@prajjwalkapoor

### CODE REVIEW

**Comment by prajjwalkapoor** [comment]
@Divyanshusir There are conflicts, do check resolve asap.

**Comment by Divyanshusir** [comment]
I have resolved it for ais/profile.html but i haven't made any changes in FusionIIIT/templates/dashboard/modules.html myself.
Changes in that are because of integration (pulled and merged ) with gad-5. 
Also this file is correct one i checked it with gad-5 updated module.
What should i do?
@prajjwalkapoor

**Comment by Divyanshusir** [comment]
@prajjwalkapoor  now conflicts have been resolved, please merge it

**Comment by ChaudharyRaman** [comment]
LGTM

**Comment by ChaudharyRaman** [comment]
@abhi87374 Can move forward for the integration.

**Pull request merged**
