### PR TITLE
Ps-1 Changes with Migrations

### PR DESCRIPTION
**Pull request by ThisisMS11**
## Features implemented
1.  Implemented file tracking SDK in inbox, file forwarding, file creation and in various places.
2.  Added Outbox API's and It is implemented using file tracking SDK.
3.  Added global transfer execution and dept transfer execution functionality.
4.  Corrected the existing code for various API's. 
5.  Fetched the new Dashboard changes. 
6.  Implemented Stock Transfer between departments by dept_admin and ps_admin
7.  Added Apis for obtaining individual stock Item information like current_department,physical location .
8.  Implement filter based lookup for stocks belong to different departments.

## Types of changes

Put an x in the boxes that apply

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

Put an x in the boxes that apply

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

Video Explaination for changes : https://drive.google.com/file/d/1gZTVEtmbG3Nn0B47LqcmYRcy0Bt94AQp/view?usp=sharing

### CODE REVIEW

**Comment by ThisisMS11** [comment]
@varun7singh please review the PR .

**Comment by prajjwalkapoor** [comment]
Change seems okay, make sure you have updated your code with the latest `gad-4` branch.

**Review by Bhavik-ag — COMMENTED** [review]
Changes LGTM !!

@Priyansh61 @theoden42 please review the merged changes of gad-4 module and verify if the integration is properly done

**Comment by Aragorn-64** [comment]
Implementation of FTS in PS-1 looks good and seems to be working as per the video shared.
@prajjwalkapoor

**Comment by prajjwalkapoor** [comment]
Alright, Merging.

**Pull request merged**
