### PR TITLE
ac 2 : Added Time feature in academic information and flexibility in pre registration filtering

### PR DESCRIPTION
**Pull request by Anunaya07**
## Proposed changes
Added Time feature in academic information
flexibility in pre registration filtering

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Comment by Anunaya07** [comment]
@PranshuNayak @samay-rgb Please review this PR.

**Review by samay-rgb — APPROVED** [review]

**Comment by Aakash2611Wagh** [comment]
Approved @akshatnema

**Comment by akshatnema** [comment]
@PranshuNayak your review needed

**Review by PranshuNayak — APPROVED** [review]
@akshatnema changes in models.py are fine

**Pull request merged**
