### PR TITLE
Ac 3 Added migration files, notifications, minor changes

### PR DESCRIPTION
**Pull request by Daksh119**
> ## Issue that this pull request solves
> Closes: # (issue number)
> 
> ## Proposed changes
> ### Added migration files, notifications and some UI improvements
> ## Types of changes
> _Put an `x` in the boxes that apply_
> 
> * [x]  Bugfix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  Other (please describe):
> 
> ## Checklist
> _Put an `x` in the boxes that apply_
> 
> * [x]  My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
> * [x]  I have performed a self-review of my own code
> * [x]  I have created new branch for this pull request
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings
> * [x]  My changes does not break the current system and it passes all the current test cases.
>
> ## Video
> https://drive.google.com/file/d/1-P5nUdyaw1OFBKrjV88aNoFrtuV-MJfm/view?usp=sharing

> ## Other information
> Any other information that is important to this pull request

### CODE REVIEW

**Comment by Priyansh61** [comment]
@Daksh119 kindly complete the PR template, wont be able to review without that

**Comment by Daksh119** [comment]
Sure

**Comment by Daksh119** [comment]
@ChaudharyRaman

**Comment by ChaudharyRaman** [comment]
@Daksh119  can you remove all the migrations manually and push ??

**Comment by Daksh119** [comment]
@ChaudharyRaman I can but I added them only because we were instructed to do so.

**Comment by Priyansh61** [comment]
@ChaudharyRaman PTAL

**Comment by ChaudharyRaman** [comment]
LGTM Merging !!!

**Pull request merged**
