### PR TITLE
GAD1 : Week1 : Fixed-Request are getting submitted with null values for request_to. 

### PR DESCRIPTION
**Pull request by CHOUHAN-MOHIT**
## Request are getting submitted with null values for request_to

Closes: # (1002)
Now the student has to provide all the information like request type, request_to and request details to make a successful request.
image
image

### CODE REVIEW

**Review by Sha2nkGitHub — COMMENTED** [review]
Approved.
Ping @akshatnema @manavdesai27

**Review by Sha2nkGitHub — COMMENTED** [review]
Approved.
Ping @akshatnema
Ping @manavdesai27

**Review by Sha2nkGitHub — COMMENTED** [review]
@CHOUHAN-MOHIT  please give reason for doing this. submit button needs to be inside "form" element.

**Comment by manavdesai27** [comment]
@Sha2nkGitHub Is this still approved?

**Review by Sha2nkGitHub — APPROVED** [review]
Yes approved

**Pull request merged**
