### PR TITLE
Issue #642 resolved

### PR DESCRIPTION
**Pull request by supr158**
Issue resolved.
Added warning in forms having dropdowns.

### CODE REVIEW

**Comment by supr158** [comment]
@anurag0singh please review this PR.

**Review by anurag0singh — COMMENTED** [review]
This branch has conflicts with the main branch of the repo. Please resolve it if possible.

**Comment by supr158** [comment]
@anurag0singh Resolved the merge conflicts.You can check it

**Review by anurag0singh — APPROVED** [review]
@MananJethwani Please merge this PR.

**Pull request merged**
