### PR TITLE
Otheracademic 2024

### PR DESCRIPTION
**Pull request by xenouno**
## Issue that this pull request solves

Closes: # (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by ChaudharyRaman** [comment]
@xenouno please upload the walk-through video for the changes that you had made and also remove all the migrations files and .DS_Store file

**Comment by xenouno** [comment]
i have removed migrations files and .DS_Store files

**Comment by xenouno** [comment]
[https://drive.google.com/drive/folders/1I7mkqBGoqmF0bX2ZKCe_LUglEfQHNWsM?usp=sharing](url)
Video for changes

**Comment by xenouno** [comment]
[https://drive.google.com/drive/folders/1I7mkqBGoqmF0bX2ZKCe_LUglEfQHNWsM?usp=sharing](url)

**Comment by xenouno** [comment]
https://drive.google.com/drive/folders/1I7mkqBGoqmF0bX2ZKCe_LUglEfQHNWsM?usp=sharing

video for changes

**Pull request merged**
