### PR TITLE
GAD-4: Fix edit draft functionality and usertype Access 

### PR DESCRIPTION
**Pull request by Aragorn-64**
## Issue that this pull request solves

Closes: # (issue number)

### Brief description of what is fixed or changed
Edit drafts now uses Dropdown designation, 
Forward file now uses Dropdown designation, 
Error on "Faculty" or "Staff" dropdown opening /filetracking now gives meaningful message
Save as draft now saves the remarks added

## Types of changes
Bug fixes and 1 addition of invalid_designation decorator

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Screenshot from 2024-04-11 01-15-47
Screenshot from 2024-04-11 01-16-01

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by Aragorn-64** [comment]
@prajjwalkapoor Please take a look, thanks

**Comment by Priyansh61** [comment]
@Aragorn-64 Can you add a screen cast of the feature or the change made in the PR? Thanks

**Comment by theoden42** [comment]
@Bhavik-ag @Priyansh61 Here is the link for the screen cast [Video Link](https://drive.google.com/file/d/1YfBH5WVreQVWWf87bNQS-66zjAavvQrC/view?usp=sharing)

The testing of GAD-4 identified some issues which were caused by update in the  dashboard: 

- The dashboard had options such as 'faculty' and 'staff'  which are userTypes, but FTS requires specific designations like 'Professor', 'HOD' to function. To fix this, we created a decorator which would redirect to a page signifying the same. 

- Edit Draft was not updated to include designations from those used in the sessions(dashboard) and is now working

- Same as above for forward file

**Review by arminpatel — APPROVED** [review]

**Review by Bhavik-ag — APPROVED** [review]
LGTM :rocket: !!

**Comment by theoden42** [comment]
@prajjwalkapoor pls merge this PR

**Pull request merged**
