### PR TITLE
AC-4 Other-academic procedures (minor changes)

### PR DESCRIPTION
**Pull request by xenouno**
added verification in leaveForm, assistantship,bonafide form

changed some fields in the above forms

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by xenouno** [comment]
@ChaudharyRaman

**Comment by Kaushals112** [comment]
@ChaudharyRaman Please merege my pr fts part is reviewed by divyansh, just i add the functionality of notifications.So,please merge my pr

**Comment by xenouno** [comment]
@prajjwalkapoor please merge this pr there are only small changes

**Comment by VarunGitGood** [comment]
@xenouno Please quickly remove all the migration files also make sure that migration folder have init file only.
Otherwise LGTM .

**Comment by xenouno** [comment]
@varun7singh i have removed the migration files

**Comment by Kaushals112** [comment]
@varun7singh @ChaudharyRaman please raise pr of latest staging as Anudeep(integration team) demanding latest staging pr for integration purpose.As evaluation is this week so please raise asap.

**Pull request merged**
